# Copyright Barry Rowlingson <b.rowlingson@lancaster.ac.uk> and 
# Peter Diggle (c) 1991-3; http://www.maths.lancs.ac.uk/~rowlings/Splancs/
# R port: copyright 1998-2000 by Roger S. Bivand

splancs <- function()
{
#	cat('Splancs version 2.00     Date 23/11/93\n')
#	cat('\n(c) BSR and PJD 1991      Lancaster University\n')
#	cat('                          Lancaster, U.K.\n')
#	cat('\n This version of Splancs is not public domain and\n')
#	cat('must not be copied or redistributed without prior\n')
#	cat('permission of the authors\n')
	'2.01'
}
